In [33]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [34]:
df = pd.read_excel('/content/DataSet (1) copy.xlsx', sheet_name='DataSet')

In [35]:
df.head()

,Product_Name,page_path_clean,Page_Path,event_date,product_position,clickouts,page_level_sessions,conversions,ctr,tier_revenue_per_clickout,tier_revenue_per_conversion,conversion_rate,approval_rate,earning_per_visitor
0,Ivory,/advisor/l/huge-cash-back-0-apr-citi-cc-pn/,Page41,2024-09-09,1.0,14.0,352.0,2.0,0.039773,71.428571,500.0,0.142857,1.000,2.840909
1,LightPink,/advisor/l/credit-cards-best-reward-credit-cards/,Page36,2025-01-08,1.0,1.0,1256.0,1.0,0.000796,800.000000,800.0,1.000000,1.000,0.636943
2,LightPink,/advisor/l/credit-cards-best-reward-credit-cards/,Page36,2025-01-07,1.0,4.0,1256.0,1.0,0.003185,200.000000,800.0,0.250000,1.000,0.636943
3,DoubleOrange,/advisor/l/best-cash-back-credit-cards-m-v2/,Page4,2025-03-21,1.0,3.0,396.0,1.0,0.007576,66.666667,200.0,0.333333,1.000,0.505051
4,DoubleOrange,/advisor/l/break-free-citi-dc-pn/,Page21,2024-09-08,1.0,55.0,1587.0,3.0,0.034657,13.636364,250.0,0.054545,0.375,0.472590

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33789 entries, 0 to 33788
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Product_Name                 26517 non-null  object
 1   page_path_clean              33712 non-null  object
 2   Page_Path                    33712 non-null  object
 3   event_date                   33712 non-null  datetime64[ns]
 4   product_position             31953 non-null  float64
 5   clickouts                    33712 non-null  float64
 6   page_level_sessions          33712 non-null  float64
 7   conversions                  33712 non-null  float64
 8   ctr                          33712 non-null  float64
 9   tier_revenue_per_clickout    14248 non-null  float64
 10  tier_revenue_per_conversion  5256 non-null   float64
 11  conversion_rate              20747 non-null  float64
 12  approval_rate                7581 non-null   float64
 13  earning_per_visitor          14248 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(3)
memory usage: 3.6+ MB

In [37]:
print(df['page_level_sessions'].isna().sum())
df['page_level_sessions'].value_counts()

77

page_level_sessions
157562.0    5376
210906.0    5143
117600.0    3825
32329.0     3193
19409.0     2658
24674.0     2213
9727.0      2201
13276.0     2025
10912.0     1873
40121.0      791
16146.0      730
1256.0       605
14838.0      534
1392.0       408
729.0        345
3453.0       339
1848.0       293
2714.0       155
4548.0       140
396.0        131
930.0        105
174.0         78
87.0          64
1587.0        59
17.0          50
66.0          48
352.0         43
42.0          41
8.0           32
14.0          28
59.0          27
11.0          22
19.0          19
9.0           18
5.0           15
13.0          13
12.0          12
4.0           12
6.0           12
7.0           11
10.0          10
1.0            8
2.0            4
3.0            3
Name: count, dtype: int64

In [38]:
# 1.There are missing values observed in the dataset.


# 2. One column is datetime, and 3 are obj/categorical columns and rest are float/numeric columns.


# 3. Product name has missing values which suggests, user might have clicked on the product but it might not have been captured.
#    Hence dropped the values of product, as it might be mapped to the wrong order.


# 4. Since we don't know here what was the core reason to put product_postion at specifiec place it will be risky to impute the values(
#    example rank 1 at 100 clicks might not make any sense however rank 1 within<5 clicks it makes sense, which is also vague to interpret).


# 5. page level session - We don't want to capture the unknown click, as it is totally on the user. As mentioned even if it is the best product
#    It is not guaranteed, this click will be good, or user is going to spent good time in that session.

In [39]:
df_copy = df.copy()

In [40]:
df_clean = df_copy.dropna(subset=['Product_Name', 'product_position', 'page_level_sessions'])

In [41]:
production_position_at_zero = df_clean[df_clean['product_position'] == 0]
print(production_position_at_zero.shape)
production_position_at_zero.head()

(546, 14)

,Product_Name,page_path_clean,Page_Path,event_date,product_position,clickouts,page_level_sessions,conversions,ctr,tier_revenue_per_clickout,tier_revenue_per_conversion,conversion_rate,approval_rate,earning_per_visitor
187,PaleVioletRed,Page3,Page64,2025-03-24,0.0,2.0,10912.0,1.0,0.000183,400.000000,800.0,0.500000,1.0,0.073314
268,Salmon,Page3,Page64,2025-03-24,0.0,19.0,10912.0,2.0,0.001741,34.210526,325.0,0.105263,1.0,0.059567
294,Lavender,Page3,Page64,2025-03-26,0.0,38.0,10912.0,2.0,0.003482,15.789474,300.0,0.052632,1.0,0.054985
474,Plum,/advisor/l/best-balance-transfer-credit-cards-v2/,Page3,2025-03-22,0.0,18.0,9727.0,2.0,0.001851,22.222222,200.0,0.111111,1.0,0.041123
491,Plum,/advisor/l/best-balance-transfer-credit-cards-v2/,Page3,2025-03-20,0.0,16.0,9727.0,2.0,0.001645,25.000000,200.0,0.125000,1.0,0.041123

In [42]:
# clearly we can observe the data has those values whose product_position is 0 which doesnot make sense.
# Hence we will capture those data points whose product_position>0

In [43]:
df_clean = df_clean[df_clean['product_position'] > 0]

In [44]:
df_clean.shape

(24363, 14)

In [45]:
df.shape

(33789, 14)

In [46]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24363 entries, 0 to 33764
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Product_Name                 24363 non-null  object
 1   page_path_clean              24363 non-null  object
 2   Page_Path                    24363 non-null  object
 3   event_date                   24363 non-null  datetime64[ns]
 4   product_position             24363 non-null  float64
 5   clickouts                    24363 non-null  float64
 6   page_level_sessions          24363 non-null  float64
 7   conversions                  24363 non-null  float64
 8   ctr                          24363 non-null  float64
 9   tier_revenue_per_clickout    13101 non-null  float64
 10  tier_revenue_per_conversion  5073 non-null   float64
 11  conversion_rate              19064 non-null  float64
 12  approval_rate                7337 non-null   float64
 13  earning_per_visitor          13101 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(3)
memory usage: 2.8+ MB

In [50]:
# tier_revenue_per_conversion is missing meaning Realized revenue is missing, meaning user dropped out hence imputing it with 0
fill_na_with_zero_cols = ['tier_revenue_per_conversion','tier_revenue_per_clickout']
df_clean[fill_na_with_zero_cols] = df_clean[fill_na_with_zero_cols].fillna(0)

In [51]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24363 entries, 0 to 33764
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Product_Name                 24363 non-null  object
 1   page_path_clean              24363 non-null  object
 2   Page_Path                    24363 non-null  object
 3   event_date                   24363 non-null  datetime64[ns]
 4   product_position             24363 non-null  float64
 5   clickouts                    24363 non-null  float64
 6   page_level_sessions          24363 non-null  float64
 7   conversions                  24363 non-null  float64
 8   ctr                          24363 non-null  float64
 9   tier_revenue_per_clickout    24363 non-null  float64
 10  tier_revenue_per_conversion  24363 non-null  float64
 11  conversion_rate              19064 non-null  float64
 12  approval_rate                7337 non-null   float64
 13  earning_per_visitor          13101 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(3)
memory usage: 2.8+ MB

In [54]:
df_clean['conversion_rate_per_clickout'] = df_clean['conversions']/df_clean['clickouts']
df_clean.sample(10)
# df_cle

,Product_Name,page_path_clean,Page_Path,event_date,product_position,clickouts,page_level_sessions,conversions,ctr,tier_revenue_per_clickout,tier_revenue_per_conversion,conversion_rate,approval_rate,earning_per_visitor,conversion_rate_per_clickout
5773,SpringGreen,/advisor/l/best-student-credit-cards-v2/,Page15,2024-09-10,4.0,18.0,24674.0,0.0,0.000730,0.0,0.0,0.0,0.0,0.0,0.0
21294,GOLD,/advisor/l/best-travel-credit-cards-v2/,Page19,2024-11-26,1.0,3.0,117600.0,0.0,0.000026,0.0,0.0,0.0,NaN,NaN,0.0
19347,YellowPink,/advisor/l/best-balance-transfer-credit-cards-...,Page1,2025-02-25,1.0,1.0,13276.0,0.0,0.000075,0.0,0.0,0.0,NaN,NaN,0.0
9828,PaleVioletRed,Page3,Page64,2025-02-20,7.0,1.0,10912.0,0.0,0.000092,0.0,0.0,0.0,0.0,0.0,0.0
8938,DoubleOrange,/advisor/l/credit-cards-best-reward-credit-car...,Page35,2024-10-19,1.0,3.0,157562.0,0.0,0.000019,0.0,0.0,0.0,NaN,0.0,0.0
24916,Orange,/advisor/l/credit-cards-best-reward-credit-car...,Page35,2025-01-16,8.0,51.0,157562.0,0.0,0.000324,0.0,0.0,0.0,NaN,NaN,0.0
17770,Salmon,Page7,Page68,2024-12-12,1.0,0.0,1392.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN
5868,DarkKhaki,/advisor/l/best-student-credit-cards-v2/,Page15,2025-03-01,2.0,11.0,24674.0,0.0,0.000446,0.0,0.0,0.0,NaN,0.0,0.0
16248,Yellow,/advisor/l/best-student-credit-cards-v2/,Page15,2025-02-10,1.0,3.0,24674.0,0.0,0.000122,0.0,0.0,0.0,NaN,NaN,0.0
14103,DodgerBlue,/advisor/l/best-credit-cards-business-m-v2/,Page8,2025-02-24,1.0,1.0,3453.0,0.0,0.000290,0.0,0.0,0.0,NaN,0.0,0.0